#!/bin/sh
# ---
# PLSPUTMEAT: /usr/bin/rofi-pm
# PLSOWNME: root
# PLSGRPME: root
# PLSMODME: 555
# ---

[ "$#" -eq 0 ] && {
	echo "shutdown"
	echo "logout"
	exit 0
}

[ "$1" = "yes" ] && {
	[ "$ROFI_DATA" = "shutdown" ] && shutdown 0
	[ "$ROFI_DATA" = "logout" ] && hyprctl dispatch exit
	exit 0
}

[ "$1" = "no" ] && {
	echo "shutdown"
	echo "logout"
	exit 0
}


[ "$1" = "shutdown" ] && printf "\0data\x1fshutdown\n"
[ "$1" = "logout" ] && printf "\0data\x1flogout\n"

printf "\0message\x1fYou sure?\n"
echo "yes"
echo "no"

